name: paybis_com_shifts
description: Paybis Shifts for customer support

version: 2.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.1+4
  firebase_auth: ^0.14.0+8
  google_sign_in: ^4.0.12
  cloud_firestore: ^0.12.10
#  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.0.8
  cloud_functions: ^0.4.1+1
#  path_provider: ^1.3.0
  timeago: ^2.0.20
  flutter_screenutil: ^0.6.0
  grouped_buttons: ^1.0.4
#  firebase_messaging: ^5.1.8
  datetime_picker_formfield: ^0.4.3
  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/PBlogo.jpg"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/