name: paybis_com_shifts
description: Paybis Shifts for customer support

version: 3.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.0+1
#  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.1.1
  cloud_functions: ^0.4.1+8
#  path_provider: ^1.3.0
  timeago: ^2.0.25
  flutter_screenutil: ^1.0.2
  grouped_buttons: ^1.0.4
  firebase_messaging: ^6.0.9
  datetime_picker_formfield: ^1.0.0
  flutter_launcher_icons: ^0.7.4
  device_info: ^0.4.1+4
  http: ^0.12.0+4
  notification_permissions: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/PBlogo.jpg"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/