name: paybis_com_shifts
description: Paybis Shifts for customer support

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+2
  google_sign_in: ^4.0.6
  cloud_firestore: ^0.12.9
  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.0.5
  modal_progress_hud: ^0.1.3
  date_format: ^1.0.6
  path_provider: ^1.2.0
  flutter_launcher_icons: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo1.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/